nationalities = {
    'afghan' : 'afghanistan',
    'afghanistan' : 'afghanistan',
    'africa' : 'africa',
    'african' : 'africa',
    'albania' : 'albania',
    'albanian' : 'albania',
    'algeria' : 'algeria',
    'algerian' : 'algeria',
    'america' : 'usa',
    'american' : 'usa',
    'andorra' : 'andorra',
    'andorran' : 'andorra',
    'angola' : 'angola',
    'angolan' : 'angola',
    'argentina' : 'argentina',
    'argentinian' : 'argentina',
    'armenia' : 'armenia',
    'armenian' : 'armenia',
    'asia' : 'asia',
    'asian' : 'asia',
    'aussie' : 'australia',
    'australia' : 'australia',
    'australian' : 'australia',
    'austria' : 'austria',
    'austrian' : 'austria',
    'azerbaijan' : 'azerbaijan',
    'azerbaijani' : 'azerbaijan',
    'bahamas' : 'bahamas',
    'bahamian' : 'bahamas',
    'bahrain' : 'bahrain',
    'bahraini' : 'bahrain',
    'bangladesh' : 'bangladesh',
    'bangladeshi' : 'bangladesh',
    'barbadian' : 'barbados',
    'barbados' : 'barbados',
    'belarus' : 'belarus',
    'belarusian' : 'belarus',
    'belgian' : 'belgium',
    'belgium' : 'belgium',
    'belize' : 'belize',
    'belizian' : 'belize',
    'benin' : 'benin',
    'beninese' : 'benin',
    'bhutan' : 'bhutan',
    'bhutanese' : 'bhutan',
    'bolivia' : 'bolivia',
    'bolivian' : 'bolivia',
    'bosnia-herzegovina' : 'bosnia-herzegovina',
    'bosnian' : 'bosnia-herzegovina',
    'botswana' : 'botswana',
    'botswanan' : 'botswana',
    'brazil' : 'brazil',
    'brazilian' : 'brazil',
    'britain' : 'britain',
    'british' : 'britain',
    'briton' : 'britain',
    'brunei' : 'brunei',
    'bruneian' : 'brunei',
    'bulgaria' : 'bulgaria',
    'bulgarian' : 'bulgaria',
    'burkina' : 'burkina',
    'burkinese' : 'burkina',
    'burma (' : 'burma (',
    'burmese' : 'burma (',
    'burundi' : 'burundi',
    'burundian' : 'burundi',
    'cambodia' : 'cambodia',
    'cambodian' : 'cambodia',
    'cameroon' : 'cameroon',
    'cameroonian' : 'cameroon',
    'canada' : 'canada',
    'canadian' : 'canada',
    'cape verde islands' : 'cape verde islands',
    'cape verdean' : 'cape verde islands',
    'chad' : 'chad',
    'chadian' : 'chad',
    'chile' : 'chile',
    'chilean' : 'chile',
    'china' : 'china',
    'chinese' : 'china',
    'colombia' : 'colombia',
    'colombian' : 'colombia',
    'congo' : 'congo',
    'congolese' : 'congo',
    'costa rica' : 'costa rica',
    'costa rican' : 'costa rica',
    'croat' : 'croatia',
    'croatia' : 'croatia',
    'cuba' : 'cuba',
    'cuban' : 'cuba',
    'cypriot' : 'cyprus',
    'cyprus' : 'cyprus',
    'czech' : 'czech republic',
    'czech republic' : 'czech republic',
    'dane' : 'denmark',
    'danish' : 'denmark',
    'denmark' : 'denmark',
    'djibouti' : 'djibouti',
    'djiboutian' : 'djibouti',
    'dominica' : 'dominica',
    'dominican' : 'dominica',
    'dominican republic' : 'dominican republic',
    'dutch' : 'holland',
    'dutchman' : 'holland',
    'dutchwoman' : 'holland',
    'ecuador' : 'ecuador',
    'ecuadorean' : 'ecuador',
    'egypt' : 'egypt',
    'egyptian' : 'egypt',
    'el salvador' : 'el salvador',
    'emirati' : 'united arab emirates',
    'england' : 'united kingdom',
    'english' : 'united kingdom',
    'englishman' : 'united kingdom',
    'englishwoman' : 'united kingdom',
    'eritrea' : 'eritrea',
    'eritrean' : 'eritrea',
    'estonia' : 'estonia',
    'estonian' : 'estonia',
    'ethiopia' : 'ethiopia',
    'ethiopian' : 'ethiopia',
    'europe' : 'europe',
    'european' : 'europe',
    'fiji' : 'fiji',
    'fijian' : 'fiji',
    'filipino' : 'philippines',
    'finland' : 'finland',
    'finn' : 'finland',
    'finnish' : 'finland',
    'france' : 'france',
    'french' : 'france',
    'frenchman' : 'france',
    'frenchwoman' : 'france',
    'gabon' : 'gabon',
    'gabonese' : 'gabon',
    'gambia, the' : 'gambia, the',
    'gambian' : 'gambia, the',
    'georgia' : 'georgia',
    'georgian' : 'georgia',
    'german' : 'germany',
    'germany' : 'germany',
    'ghana' : 'ghana',
    'ghanaian' : 'ghana',
    'greece' : 'greece',
    'greek' : 'greece',
    'grenada' : 'grenada',
    'grenadian' : 'grenada',
    'guatemala' : 'guatemala',
    'guatemalan' : 'guatemala',
    'guinea' : 'guinea',
    'guinean' : 'papua new guinea',
    'guyana' : 'guyana',
    'guyanese' : 'guyana',
    'haiti' : 'haiti',
    'haitian' : 'haiti',
    'holland' : 'holland',
    'honduran' : 'honduras',
    'honduras' : 'honduras',
    'hungarian' : 'hungary',
    'hungary' : 'hungary',
    'iceland' : 'iceland',
    'icelander' : 'iceland',
    'icelandic' : 'iceland',
    'india' : 'india',
    'indian' : 'india',
    'indonesia' : 'indonesia',
    'indonesian' : 'indonesia',
    'iran' : 'iran',
    'iranian' : 'iran',
    'iraq' : 'iraq',
    'iraqi' : 'iraq',
    'ireland' : 'ireland',
    'irish' : 'ireland',
    'irishman' : 'ireland',
    'irishwoman' : 'ireland',
    'israel' : 'israel',
    'israeli' : 'israel',
    'italian' : 'italy',
    'italy' : 'italy',
    'jamaica' : 'jamaica',
    'jamaican' : 'jamaica',
    'japan' : 'japan',
    'japanese' : 'japan',
    'jordan' : 'jordan',
    'jordanian' : 'jordan',
    'kazakh' : 'kazakhstan',
    'kazakhstan' : 'kazakhstan',
    'kenya' : 'kenya',
    'kenyan' : 'kenya',
    'korea' : 'south korea',
    'korean' : 'south korea',
    'kuwait' : 'kuwait',
    'kuwaiti' : 'kuwait',
    'laos' : 'laos',
    'laotian' : 'laos',
    'latvia' : 'latvia',
    'latvian' : 'latvia',
    'lebanese' : 'lebanon',
    'lebanon' : 'lebanon',
    'liberia' : 'liberia',
    'liberian' : 'liberia',
    'libya' : 'libya',
    'libyan' : 'libya',
    'liechtenstein' : 'liechtenstein',
    'liechtensteiner' : 'liechtenstein',
    'lithuania' : 'lithuania',
    'lithuanian' : 'lithuania',
    'luxembourg' : 'luxembourg',
    'luxembourger' : 'luxembourg',
    'macedonia' : 'macedonia',
    'macedonian' : 'macedonia',
    'madagascar' : 'madagascar',
    'malagasy' : 'madagascar',
    'malesian' : 'malesia', 
    'malesia' : 'malesia', 
    'malawi' : 'malawi',
    'malawian' : 'malawi',
    'malaysia' : 'malaysia',
    'malaysian' : 'malaysia',
    'maldives' : 'maldives',
    'maldivian' : 'maldives',
    'mali' : 'mali',
    'malian' : 'mali',
    'malta' : 'malta',
    'maltese' : 'malta',
    'mauritania' : 'mauritania',
    'mauritanian' : 'mauritania',
    'mauritian' : 'mauritius',
    'mauritius' : 'mauritius',
    'mexican' : 'mexico',
    'mexico' : 'mexico',
    'middle east' : 'middle east',
    'middle eastern' : 'middle east',
    'moldova' : 'moldova',
    'moldovan' : 'moldova',
    'monaco' : 'monaco',
    'monegasque' : 'monaco',
    'mongolia' : 'mongolia',
    'mongolian' : 'mongolia',
    'montenegrin' : 'montenegro',
    'montenegro' : 'montenegro',
    'moroccan' : 'morocco',
    'morocco' : 'morocco',
    'mozambican' : 'mozambique',
    'mozambique' : 'mozambique',
    'myanmar' : 'myanmar',
    'namibia' : 'namibia',
    'namibian' : 'namibia',
    'nepal' : 'nepal',
    'nepalese' : 'nepal',
    'netherland' : 'holland',
    'netherlands' : 'holland',
    'new zealand' : 'new zealand',
    'new zealander' : 'new zealand',
    'nicaragua' : 'nicaragua',
    'nicaraguan' : 'nicaragua',
    'niger' : 'niger',
    'nigeria' : 'nigeria',
    'nigerian' : 'nigeria',
    'nigerien' : 'niger',
    'north america' : 'north america',
    'north american' : 'north america',
    'north korea' : 'north korea',
    'north korean' : 'north korea',
    'norway' : 'norway',
    'norwegian' : 'norway',
    'oman' : 'oman',
    'omani' : 'oman',
    'ozzie' : 'australia',
    'ozzy' : 'australia',
    'pakistan' : 'pakistan',
    'pakistani' : 'pakistan',
    'panama' : 'panama',
    'panamanian' : 'panama',
    'papua new guinea' : 'papua new guinea',
    'papua new guinean' : 'papua new guinea',
    'paraguay' : 'paraguay',
    'paraguayan' : 'paraguay',
    'peru' : 'peru',
    'peruvian' : 'peru',
    'philippine' : 'philippines',
    'philippines' : 'philippines',
    'poland' : 'poland',
    'pole' : 'poland',
    'polish' : 'poland',
    'portugal' : 'portugal',
    'portuguese' : 'portugal',
    'qatar' : 'qatar',
    'qatari' : 'qatar',
    'romania' : 'romania',
    'romanian' : 'romania',
    'russia' : 'russia',
    'russian' : 'russia',
    'rwanda' : 'rwanda',
    'rwandan' : 'rwanda',
    'salvadorean' : 'el salvador',
    'saudi arabia' : 'saudi arabia',
    'saudi arabian' : 'saudi arabia',
    'scot' : 'scotland',
    'scotland' : 'scotland',
    'scottish' : 'scotland',
    'senegal' : 'senegal',
    'senegalese' : 'senegal',
    'serb' : 'serbia',
    'serbia' : 'serbia',
    'seychelles, the' : 'seychelles, the',
    'seychellois' : 'seychelles, the',
    'sierra leone' : 'sierra leone',
    'sierra leonian' : 'sierra leone',
    'singapore' : 'singapore',
    'singaporean' : 'singapore',
    'slovak' : 'slovakia',
    'slovakia' : 'slovakia',
    'slovene' : 'slovenia',
    'slovenia' : 'slovenia',
    'solomon islander' : 'solomon islands',
    'solomon islands' : 'solomon islands',
    'somali' : 'somalia',
    'somalia' : 'somalia',
    'south africa' : 'south africa',
    'south african' : 'south africa',
    'south america' : 'south america',
    'south american' : 'south america',
    'south korea' : 'south korea',
    'south korean' : 'south korea',
    'spain' : 'spain',
    'spaniard' : 'spain',
    'spanish' : 'spain',
    'sri lanka' : 'sri lanka',
    'sri lankan' : 'sri lanka',
    'sudan' : 'sudan',
    'sudanese' : 'sudan',
    'suriname' : 'suriname',
    'surinamer' : 'suriname',
    'surinamese' : 'suriname',
    'swazi' : 'swaziland',
    'swaziland' : 'swaziland',
    'swede' : 'sweden',
    'sweden' : 'sweden',
    'swedish' : 'sweden',
    'swiss' : 'switzerland',
    'switzerland' : 'switzerland',
    'syria' : 'syria',
    'syrian' : 'syria',
    'taiwan' : 'taiwan',
    'taiwanese' : 'taiwan',
    'tajik' : 'tajikistan',
    'tajikistan' : 'tajikistan',
    'tanzania' : 'tanzania',
    'tanzanian' : 'tanzania',
    'thai' : 'thailand',
    'thailand' : 'thailand',
    'the netherlands' : 'holland',
    'the philippines' : 'philippines',
    'togo' : 'togo',
    'togolese' : 'togo',
    'trinidad and tobago' : 'trinidad and tobago',
    'trinidadian' : 'trinidad and tobago',
    'tswana' : 'botswana',
    'tunisia' : 'tunisia',
    'tunisian' : 'tunisia',
    'turk' : 'turkey',
    'turkey' : 'turkey',
    'turkish' : 'turkey',
    'turkmen' : 'turkmenistan',
    'turkmenistan' : 'turkmenistan',
    'tuvali' : 'tuvali',
    'tuvaluan' : 'tuvali',
    'uae' : 'united arab emirates',
    'uganda' : 'uganda',
    'ugandan' : 'uganda',
    'uk' : 'united kingdom',
    'ukraine' : 'ukraine',
    'ukrainian' : 'ukraine',
    'united arab emirates' : 'united arab emirates',
    'united kingdom' : 'united kingdom',
    'united states of america' : 'usa',
    'uruguay' : 'uruguay',
    'uruguayan' : 'uruguay',
    'us' : 'usa',
    'us citizen' : 'usa',
    'usa' : 'usa',
    'uzbek' : 'uzbekistan',
    'uzbekistan' : 'uzbekistan',
    'vanuata' : 'vanuata',
    'vanuatuan' : 'vanuata',
    'vatican' : 'vatican',
    'vatican city' : 'vatican',
    'venezuela' : 'venezuela',
    'venezuelan' : 'venezuela',
    'vietnam' : 'vietnam',
    'vietnamese' : 'vietnam',
    'wales' : 'wales',
    'welsh' : 'wales',
    'welshman' : 'wales',
    'welshwoman' : 'wales',
    'western samoa' : 'western samoa',
    'western samoan' : 'western samoa',
    'yemen' : 'yemen',
    'yemeni' : 'yemen',
    'yugoslav' : 'yugoslavia',
    'yugoslavia' : 'yugoslavia',
    'zaire' : 'zaire',
    'zairean' : 'zaire',
    'zambia' : 'zambia',
    'zambian' : 'zambia',
    'zimbabwe' : 'zimbabwe',
    'zimbabwean' : 'zimbabwe',
    'persian' : 'iran',
    'arab' : 'arab',
    'jewish' : 'jewish',
    'palenstine' : 'palestine',
    'palenstinian' : 'palestine',
}
