professions = set([
    'accountant',
    'accounts assistant',
    'accounts clerk',
    'accounts manager',
    'accounts staff',
    'accountsassistant',
    'accountsclerk',
    'accountsmanager',
    'accountsstaff',
    'acoustic engineer',
    'acousticengineer',
    'actor',
    'actress',
    'actuary',
    'acupuncturist',
    'adjustor',
    'administration assistant',
    'administration clerk',
    'administration manager',
    'administration staff',
    'administrationassistant',
    'administrationclerk',
    'administrationmanager',
    'administrationstaff',
    'administrator',
    'advertising agent',
    'advertising assistant',
    'advertising clerk',
    'advertising contractor',
    'advertising executive',
    'advertising manager',
    'advertising staff',
    'advertisingagent',
    'advertisingassistant',
    'advertisingclerk',
    'advertisingcontractor',
    'advertisingexecutive',
    'advertisingmanager',
    'advertisingstaff',
    'aerial erector',
    'aerialerector',
    'aerobic / keep fit instructor',
    'aerobic instructor',
    'aerobic/keepfitinstructor',
    'aerobicinstructor',
    'aeronautical engineer',
    'aeronauticalengineer',
    'agent',
    'agricultural consultant',
    'agricultural contractor',
    'agricultural engineer',
    'agricultural merchant',
    'agricultural worker',
    'agriculturalconsultant',
    'agriculturalcontractor',
    'agriculturalengineer',
    'agriculturalmerchant',
    'agriculturalworker',
    'air force',
    'air traffic controller',
    'aircraft',
    'aircraft buyer',
    'aircraft designer',
    'aircraft engineer',
    'aircraft maintenance engineer',
    'aircraft surface finisher',
    'aircraftbuyer',
    'aircraftdesigner',
    'aircraftengineer',
    'aircraftmaintenanceengineer',
    'aircraftsurfacefinisher',
    'airforce',
    'airline employee',
    'airlineemployee',
    'airman',
    'airport controller',
    'airport manager',
    'airportcontroller',
    'airportmanager',
    'airtrafficcontroller',
    'almoner',
    'ambulance controller',
    'ambulance crew',
    'ambulance driver',
    'ambulancecontroller',
    'ambulancecrew',
    'ambulancedriver',
    'amusement arcade worker',
    'amusementarcadeworker',
    'anaesthetist',
    'analytical chemist',
    'analyticalchemist',
    'animal breeder',
    'animalbreeder',
    'anthropologist',
    'antique dealer',
    'antiquedealer',
    'applications engineer',
    'applications programmer',
    'applicationsengineer',
    'applicationsprogrammer',
    'arbitrator',
    'arborist',
    'archaeologist',
    'architect',
    'architects',
    'architectural',
    'archivist',
    'area manager',
    'areamanager',
    'armourer',
    'army officer',
    'armyman',
    'armyofficer',
    'aromatherapist',
    'art critic',
    'art dealer',
    'art historian',
    'art restorer',
    'artcritic',
    'artdealer',
    'artexer',
    'arthistorian',
    'articled clerk',
    'articledclerk',
    'artificial limb fitter',
    'artificiallimbfitter',
    'artist',
    'artrestorer',
    'arts',
    'asbestos remover',
    'asbestosremover',
    'asphalter',
    'assembly worker',
    'assemblyworker',
    'assessor',
    'assistant',
    'assistant accounts',
    'assistant caretaker',
    'assistant cook',
    'assistant manager',
    'assistant nurse',
    'assistant teacher',
    'assistantaccounts',
    'assistantcaretaker',
    'assistantcook',
    'assistantmanager',
    'assistantnurse',
    'assistantteacher',
    'astrologer',
    'astronomer',
    'attendant',
    'au pair',
    'auction worker',
    'auctioneer',
    'auctionworker',
    'audiologist',
    'audit clerk',
    'audit manager',
    'auditclerk',
    'auditmanager',
    'auditor',
    'aupair',
    'author',
    'auto electrician',
    'autoelectrician',
    'auxiliary nurse',
    'auxiliarynurse',
    'bacon curer',
    'baconcurer',
    'baggage handler',
    'baggagehandler',
    'bailiff',
    'baker',
    'bakery assistant',
    'bakery manager',
    'bakery operator',
    'bakeryassistant',
    'bakerymanager',
    'bakeryoperator',
    'balloonist',
    'band',
    'bank clerk',
    'bank manager',
    'bank messenger',
    'bank note checker',
    'bank staff',
    'bankclerk',
    'bankmanager',
    'bankmessenger',
    'banknotechecker',
    'bankstaff',
    'baptist minister',
    'baptistminister',
    'bar manager',
    'bar staff',
    'bar steward',
    'barber',
    'barmaid',
    'barman',
    'barmanager',
    'barrister',
    'barstaff',
    'barsteward',
    'beautician',
    'beauty therapist',
    'beautytherapist',
    'betting shop',
    'bettingshop',
    'bill poster',
    'billposter',
    'bingo caller',
    'bingo hall staff',
    'bingocaller',
    'bingohallstaff',
    'biochemist',
    'biologist',
    'blacksmith',
    'blind assembler',
    'blind fitter',
    'blindassembler',
    'blindfitter',
    'blinds installer',
    'blindsinstaller',
    'boat builder',
    'boatbuilder',
    'body fitter',
    'bodyfitter',
    'bodyguard',
    'bodyshop',
    'boiler maker',
    'boiler man',
    'boilermaker',
    'boilerman',
    'book binder',
    'book keeper',
    'book seller',
    'bookbinder',
    'booking agent',
    'booking clerk',
    'booking office',
    'bookingagent',
    'bookingclerk',
    'bookingoffice',
    'bookkeeper',
    'bookmaker',
    'bookseller',
    'botanist',
    'box maker',
    'box office clerk',
    'boxmaker',
    'boxofficeclerk',
    'branch manager',
    'branchmanager',
    'breeder',
    'brewer',
    'brewery manager',
    'brewery worker',
    'brewerymanager',
    'breweryworker',
    'bricklayer',
    'broadcaster',
    'broadcasting',
    'builder',
    'builders',
    'builders labourer',
    'builderslabourer',
    'building',
    'building advisor',
    'building control',
    'building engineer',
    'building estimator',
    'building foreman',
    'building inspector',
    'building manager',
    'building site',
    'building society',
    'building surveyor',
    'buildingadvisor',
    'buildingcontrol',
    'buildingengineer',
    'buildingestimator',
    'buildingforeman',
    'buildinginspector',
    'buildingmanager',
    'buildingsite',
    'buildingsociety',
    'buildingsurveyor',
    'bursar',
    'bus company',
    'bus conductor',
    'bus driver',
    'bus mechanic',
    'bus valeter',
    'buscompany',
    'busconductor',
    'busdriver',
    'business consultant',
    'business proprietor',
    'businessconsultant',
    'businessproprietor',
    'busmechanic',
    'busvaleter',
    'butcher',
    'butchery manager',
    'butcherymanager',
    'butler',
    'buyer',
    'cabinet maker',
    'cabinetmaker',
    'cable contractor',
    'cable jointer',
    'cable tv installer',
    'cablecontractor',
    'cablejointer',
    'cabletvinstaller',
    'cafe owner',
    'cafe staff',
    'cafe worker',
    'cafeowner',
    'cafestaff',
    'cafeworker',
    'calibration manager',
    'calibrationmanager',
    'camera repairer',
    'cameraman',
    'camerarepairer',
    'canal boat broker',
    'canalboatbroker',
    'car body repairer',
    'car builder',
    'car dealer',
    'car delivery driver',
    'car park attendant',
    'car salesman',
    'car valet',
    'car wash attendant',
    'carbodyrepairer',
    'carbuilder',
    'cardealer',
    'cardeliverydriver',
    'care assistant',
    'care manager',
    'careassistant',
    'careers advisor',
    'careers officer',
    'careersadvisor',
    'careersofficer',
    'caremanager',
    'carer, non',
    'carer,non',
    'caretaker',
    'cargo operator',
    'cargooperator',
    'carparkattendant',
    'carpenter',
    'carpenters',
    'carpet cleaner',
    'carpet fitter',
    'carpet retailer',
    'carpetcleaner',
    'carpetfitter',
    'carpetretailer',
    'carphone fitter',
    'carphonefitter',
    'carsalesman',
    'cartographer',
    'cartoonist',
    'carvalet',
    'carwashattendant',
    'cash point fitter',
    'cashier',
    'cashpointfitter',
    'casual worker',
    'casualworker',
    'caterer',
    'catering consultant',
    'catering manager',
    'catering staff',
    'cateringconsultant',
    'cateringmanager',
    'cateringstaff',
    'caulker',
    'ceiling contractor',
    'ceiling fixer',
    'ceilingcontractor',
    'ceilingfixer',
    'cellarman',
    'centre lathe',
    'centrelathe',
    'certified',
    'chambermaid',
    'chandler',
    'chaplain',
    'charge hand',
    'chargehand',
    'charity worker',
    'charityworker',
    'chartered',
    'charterer',
    'chauffeur',
    'check out assistant',
    'checkoutassistant',
    'chef',
    'chemical',
    'chemist',
    'chicken chaser',
    'chicken sexer',
    'chickenchaser',
    'chickensexer',
    'chief cashier',
    'chief chemist',
    'chief executive',
    'chiefcashier',
    'chiefchemist',
    'chiefexecutive',
    'child minder',
    'childminder',
    'childrens',
    'chimney sweep',
    'chimneysweep',
    'china restorer',
    'chinarestorer',
    'chiropodist',
    'chiropractor',
    'choreographer',
    'church officer',
    'church warden',
    'churchofficer',
    'churchwarden',
    'cinema',
    'cinema manager',
    'cinemamanager',
    'circus proprietor',
    'circus worker',
    'circusproprietor',
    'circusworker',
    'civil engineer',
    'civil servant',
    'civilengineer',
    'civilservant',
    'claims adjustor',
    'claims assessor',
    'claims manager',
    'claims/loss',
    'claimsadjustor',
    'claimsassessor',
    'claimsmanager',
    'clairvoyant',
    'classical',
    'classroom aide',
    'classroomaide',
    'clay pigeon',
    'claypigeon',
    'cleaner',
    'cleaning',
    'clergyman',
    'cleric',
    'clerical assistant',
    'clerical officer',
    'clericalassistant',
    'clericalofficer',
    'clerk',
    'clerk of works',
    'clerkofworks',
    'clinical',
    'clock maker',
    'clockmaker',
    'coach',
    'coach builder',
    'coach driver',
    'coach sprayer',
    'coachbuilder',
    'coachdriver',
    'coachsprayer',
    'coal merchant',
    'coalmerchant',
    'coastguard',
    'cobbler',
    'coffee merchant',
    'coffeemerchant',
    'coin dealer',
    'coindealer',
    'collector',
    'college dean',
    'college lecturer',
    'college principal',
    'collegedean',
    'collegelecturer',
    'collegeprincipal',
    'commercial artist',
    'commercial manager',
    'commercial traveller',
    'commercialartist',
    'commercialmanager',
    'commercialtraveller',
    'commission agent',
    'commissionagent',
    'commissionaire',
    'commissioned',
    'commissioning',
    'commodity broker',
    'commodity dealer',
    'commoditybroker',
    'commoditydealer',
    'communications',
    'community craft',
    'community nurse',
    'community worker',
    'communitycraft',
    'communitynurse',
    'communityworker',
    'company chairman',
    'company director',
    'company search',
    'company secretary',
    'companychairman',
    'companydirector',
    'companysearch',
    'companysecretary',
    'complementary',
    'composer',
    'compositor',
    'computer',
    'computer analyst',
    'computer consultant',
    'computer engineer',
    'computer manager',
    'computer operator',
    'computer technician',
    'computeranalyst',
    'computerconsultant',
    'computerengineer',
    'computermanager',
    'computeroperator',
    'computertechnician',
    'computing',
    'confectioner',
    'conference',
    'conference manager',
    'conferencemanager',
    'conservationist',
    'conservator',
    'construction',
    'construction worker',
    'constructionworker',
    'consultant',
    'consultant engineer',
    'consultantengineer',
    'contract cleaner',
    'contract furnisher',
    'contract manager',
    'contractcleaner',
    'contractfurnisher',
    'contractmanager',
    'contractor',
    'contracts supervisor',
    'contractssupervisor',
    'conveyancer',
    'cook',
    'cooper',
    'coppersmith',
    'copywriter',
    'coroner',
    'corrosion',
    'costume',
    'costume jeweller',
    'costumejeweller',
    'costumier',
    'council worker',
    'councilworker',
    'counsellor',
    'countryside',
    'county councillor',
    'countycouncillor',
    'courier',
    'court officer',
    'courtofficer',
    'craft dealer',
    'craftdealer',
    'craftsman',
    'craftswoman',
    'crane driver',
    'crane erector',
    'crane operator',
    'cranedriver',
    'craneerector',
    'craneoperator',
    'creche worker',
    'crecheworker',
    'credit broker',
    'credit control',
    'credit controller',
    'credit draper',
    'credit manager',
    'creditbroker',
    'creditcontrol',
    'creditcontroller',
    'creditdraper',
    'creditmanager',
    'crematorium',
    'crime examiner',
    'crimeexaminer',
    'crofter',
    'croupier',
    'crown prosecutor',
    'crownprosecutor',
    'curator',
    'currency trader',
    'currencytrader',
    'curtain maker',
    'curtainmaker',
    'customer advisor',
    'customer liaison',
    'customeradvisor',
    'customerliaison',
    'customs',
    'cutler',
    'cutter',
    'cycle repairer',
    'cyclerepairer',
    'dairy engineer',
    'dairy worker',
    'dairyengineer',
    'dairyworker',
    'dance teacher',
    'dancer',
    'danceteacher',
    'dark room',
    'darkroom',
    'data',
    'data coordinator',
    'data processor',
    'datacoordinator',
    'dataprocessor',
    'day care officer',
    'daycareofficer',
    'dealer',
    'debt collector',
    'debt counsellor',
    'debtcollector',
    'debtcounsellor',
    'decorator',
    'delivery',
    'delivery courier',
    'delivery driver',
    'delivery roundsman',
    'deliverycourier',
    'deliverydriver',
    'deliveryroundsman',
    'demolition worker',
    'demolitionworker',
    'demonstrator',
    'dendrochronologist',
    'dental assistant',
    'dental hygienist',
    'dental nurse',
    'dental surgeon',
    'dental technician',
    'dentalassistant',
    'dentalhygienist',
    'dentalnurse',
    'dentalsurgeon',
    'dentaltechnician',
    'dentist',
    'dentist/dentition',
    'deputy head teacher',
    'deputy manager',
    'deputy principal',
    'deputyheadteacher',
    'deputymanager',
    'deputyprincipal',
    'dermatologist',
    'design director',
    'design engineer',
    'design manager',
    'designdirector',
    'designengineer',
    'designer',
    'designer industrial',
    'designerindustrial',
    'designmanager',
    'despatch driver',
    'despatch rider',
    'despatch worker',
    'despatchdriver',
    'despatchrider',
    'despatchworker',
    'development',
    'diamond dealer',
    'diamonddealer',
    'diecaster',
    'dietician',
    'dinner lady',
    'dinnerlady',
    'diplomat',
    'diplomatic staff',
    'diplomaticstaff',
    'director',
    'disc jockey',
    'discjockey',
    'disco staff',
    'discostaff',
    'distillery worker',
    'distilleryworker',
    'distribution manager',
    'distributionmanager',
    'district nurse',
    'district valuer',
    'districtnurse',
    'districtvaluer',
    'diver',
    'docker',
    'dockyard worker',
    'dockyardworker',
    'doctor',
    'doctor medical',
    'doctormedical',
    'document controller',
    'documentcontroller',
    'dog beautician',
    'dog breeder',
    'dog groomer',
    'dog trainer',
    'dog warden',
    'dogbeautician',
    'dogbreeder',
    'doggroomer',
    'dogtrainer',
    'dogwarden',
    'doll maker',
    'dollmaker',
    'domestic staff',
    'domesticstaff',
    'door fitter',
    'door to door',
    'doorfitter',
    'doorman',
    'doortodoor',
    'double glazing',
    'doubleglazing',
    'draughtsman',
    'draughtswoman',
    'drayman',
    'dressmaker',
    'drilling technician',
    'drillingtechnician',
    'driver',
    'driver psv',
    'driverpsv',
    'driving examiner',
    'driving instructor',
    'drivingexaminer',
    'drivinginstructor',
    'drug addiction',
    'drugaddiction',
    'dry cleaner',
    'drycleaner',
    'dryliner',
    'dustman',
    'dye polisher',
    'dyepolisher',
    'dyer',
    'earth moving',
    'earthmoving',
    'ecologist',
    'economist',
    'editor',
    'editorial consultant',
    'editorial staff',
    'editorialconsultant',
    'editorialstaff',
    'education advisor',
    'education officer',
    'educationadvisor',
    'educationofficer',
    'electrical',
    'electrical engineer',
    'electrical fitter',
    'electricalengineer',
    'electricalfitter',
    'electrician',
    'electrologist',
    'electronic engineer',
    'electronicengineer',
    'electronics',
    'embalmer',
    'embassy staff',
    'embassystaff',
    'embroiderer',
    'emergency service',
    'emergencyservice',
    'employee',
    'energy analyst',
    'energyanalyst',
    'engineer',
    'engraver',
    'enquiry agent',
    'enquiryagent',
    'entertainer',
    'environmental',
    'equity agent',
    'equityagent',
    'estate agent',
    'estate manager',
    'estateagent',
    'estatemanager',
    'estimator',
    'evangelist',
    'events organiser',
    'eventsorganiser',
    'excursion manager',
    'excursionmanager',
    'executive',
    'exhaust fitter',
    'exhaustfitter',
    'exhibition designer',
    'exhibition organiser',
    'exhibitiondesigner',
    'exhibitionorganiser',
    'exotic dancer',
    'exoticdancer',
    'expedition leader',
    'expeditionleader',
    'expert',
    'export consultant',
    'exportconsultant',
    'exporter',
    'extrusion operator',
    'extrusionoperator',
    'fabricator',
    'factory canteen',
    'factory inspector',
    'factory manager',
    'factory worker',
    'factorycanteen',
    'factoryinspector',
    'factorymanager',
    'factoryworker',
    'fairground worker',
    'fairgroundworker',
    'falconer',
    'farm manager',
    'farm worker',
    'farmer',
    'farmmanager',
    'farmworker',
    'farrier',
    'fashion',
    'fashion designer',
    'fashion photographer',
    'fashiondesigner',
    'fashionphotographer',
    'fast food caterer',
    'fast food delivery',
    'fast food proprietor',
    'fastfoodcaterer',
    'fastfooddelivery',
    'fastfoodproprietor',
    'fence erecter',
    'fenceerecter',
    'fibre glass moulder',
    'fibreglassmoulder',
    'field officer',
    'fieldofficer',
    'figure painter',
    'figurepainter',
    'film director',
    'film producer',
    'film technician',
    'filmdirector',
    'filmproducer',
    'filmtechnician',
    'finance director',
    'finance manager',
    'finance officer',
    'financedirector',
    'financemanager',
    'financeofficer',
    'financial advisor',
    'financial analyst',
    'financial consultant',
    'financialadvisor',
    'financialanalyst',
    'financialconsultant',
    'financier',
    'fire officer',
    'fire prevention officer',
    'fire protection',
    'firefighter',
    'fireman/woman',
    'fireofficer',
    'fireplace fitter',
    'fireplacefitter',
    'firepreventionofficer',
    'fireprotection',
    'firewood merchant',
    'firewoodmerchant',
    'first aid worker',
    'firstaidworker',
    'fish buyer',
    'fish filleter',
    'fish fryer',
    'fish merchant',
    'fish worker',
    'fishbuyer',
    'fisheries inspector',
    'fisheriesinspector',
    'fisherman',
    'fishery manager',
    'fisherymanager',
    'fishfilleter',
    'fishfryer',
    'fishmerchant',
    'fishmonger',
    'fishworker',
    'fitness instructor',
    'fitnessinstructor',
    'fitter',
    'flagger',
    'flight deck crew',
    'flightdeckcrew',
    'floor layer',
    'floor manager',
    'floorlayer',
    'floormanager',
    'florist',
    'flour miller',
    'flourmiller',
    'flower arranger',
    'flowerarranger',
    'flying instructor',
    'flyinginstructor',
    'foam convertor',
    'foamconvertor',
    'food processor',
    'foodprocessor',
    'footballer',
    'forces foreign',
    'forcesforeign',
    'foreman',
    'forensic scientist',
    'forensicscientist',
    'forest ranger',
    'forester',
    'forestranger',
    'fork lift truck driver',
    'forklifttruckdriver',
    'forwarding agent',
    'forwardingagent',
    'foster parent',
    'fosterparent',
    'foundry worker',
    'foundryworker',
    'fraud investigator',
    'fraudinvestigator',
    'french polisher',
    'frenchpolisher',
    'fruiterer',
    'fuel merchant',
    'fuelmerchant',
    'fund raiser',
    'fundraiser',
    'funeral director',
    'funeral furnisher',
    'funeraldirector',
    'funeralfurnisher',
    'furnace man',
    'furnaceman',
    'furniture dealer',
    'furniture remover',
    'furniture restorer',
    'furnituredealer',
    'furnitureremover',
    'furniturerestorer',
    'furrier',
    'gallery owner',
    'galleryowner',
    'gambler',
    'gamekeeper',
    'gaming board inspector',
    'gaming club manager',
    'gaming club proprietor',
    'gaming club staff',
    'gamingboardinspector',
    'gamingclubmanager',
    'gamingclubproprietor',
    'gamingclubstaff',
    'garage attendant',
    'garage foreman',
    'garage manager',
    'garageattendant',
    'garageforeman',
    'garagemanager',
    'garda',
    'garden designer',
    'gardendesigner',
    'gardener',
    'gas fitter',
    'gas mechanic',
    'gas technician',
    'gasfitter',
    'gasmechanic',
    'gastechnician',
    'gate keeper',
    'gatekeeper',
    'genealogist',
    'general manager',
    'general practitioner',
    'general worker',
    'generalmanager',
    'generalpractitioner',
    'generalworker',
    'geologist',
    'geophysicist',
    'gilder',
    'glass worker',
    'glassworker',
    'glazier',
    'goldsmith',
    'golf caddy',
    'golf club professional',
    'golfcaddy',
    'golfclubprofessional',
    'golfer',
    'goods',
    'goods handler',
    'goodshandler',
    'governor',
    'granite technician',
    'granitetechnician',
    'graphic designer',
    'graphicdesigner',
    'graphologist',
    'grave digger',
    'gravedigger',
    'gravel merchant',
    'gravelmerchant',
    'green keeper',
    'greengrocer',
    'greenkeeper',
    'grocer',
    'groom',
    'ground worker',
    'groundsman',
    'groundworker',
    'group',
    'guard',
    'guest house owner',
    'guest house proprietor',
    'guesthouseowner',
    'guesthouseproprietor',
    'guide',
    'gun smith',
    'gunsmith',
    'gynaecologist',
    'hairdresser',
    'hairdresser mobile',
    'hairdressermobile',
    'handyman',
    'hardware dealer',
    'hardwaredealer',
    'haulage contractor',
    'haulagecontractor',
    'hawker',
    'head accurist',
    'head greenkeeper',
    'head lad',
    'headaccurist',
    'headgreenkeeper',
    'headlad',
    'headteacher',
    'health advisor',
    'health and safety',
    'health care assistant',
    'health consultant',
    'health nurse',
    'health officer',
    'health planner',
    'health service',
    'health therapist',
    'health visitor',
    'healthadvisor',
    'healthandsafety',
    'healthcareassistant',
    'healthconsultant',
    'healthnurse',
    'healthofficer',
    'healthplanner',
    'healthservice',
    'healththerapist',
    'healthvisitor',
    'hearing therapist',
    'hearingtherapist',
    'heating & ventilation',
    'heating engineer',
    'heating&ventilation',
    'heating/ventalation',
    'heatingengineer',
    'herbalist',
    'hgv driver',
    'hgv mechanic',
    'hgvdriver',
    'hgvmechanic',
    'highway inspector',
    'highwayinspector',
    'hire car driver',
    'hirecardriver',
    'historian',
    'hod carrier',
    'hodcarrier',
    'holiday camp staff',
    'holidaycampstaff',
    'home economist',
    'home help',
    'homecare manager',
    'homecaremanager',
    'homeeconomist',
    'homehelp',
    'homeopath',
    'homeworker',
    'hop merchant',
    'hopmerchant',
    'horse breeder',
    'horse dealer',
    'horse riding instructor',
    'horse trader',
    'horse trainer',
    'horsebreeder',
    'horsedealer',
    'horseridinginstructor',
    'horsetrader',
    'horsetrainer',
    'horticultural consultant',
    'horticulturalconsultant',
    'horticulturalist',
    'hosiery mechanic',
    'hosiery worker',
    'hosierymechanic',
    'hosieryworker',
    'hospital consultant',
    'hospital doctor',
    'hospital manager',
    'hospital orderly',
    'hospital technician',
    'hospital warden',
    'hospital worker',
    'hospitalconsultant',
    'hospitaldoctor',
    'hospitalmanager',
    'hospitalorderly',
    'hospitaltechnician',
    'hospitalwarden',
    'hospitalworker',
    'hostess',
    'hot foil printer',
    'hotel consultant',
    'hotel worker',
    'hotelconsultant',
    'hotelier',
    'hotelworker',
    'hotfoilprinter',
    'house parent',
    'househusband',
    'housekeeper',
    'houseparent',
    'housewife',
    'housing assistant',
    'housing officer',
    'housing supervisor',
    'housingassistant',
    'housingofficer',
    'housingsupervisor',
    'hydro geologist',
    'hydrogeologist',
    'hygienist',
    'hypnotherapist',
    'hypnotist',
    'ice cream vendor',
    'icecreamvendor',
    'illustrator',
    'immigration officer',
    'immigrationofficer',
    'import consultant',
    'importconsultant',
    'importer',
    'independent means',
    'independentmeans',
    'induction moulder',
    'inductionmoulder',
    'industrial chemist',
    'industrial consultant',
    'industrialchemist',
    'industrialconsultant',
    'injection moulder',
    'injectionmoulder',
    'inland revenue officer',
    'inlandrevenueofficer',
    'inspector',
    'inspector insurance',
    'inspectorinsurance',
    'installers',
    'instructor',
    'instrument engineer',
    'instrument maker',
    'instrument supervisor',
    'instrument technician',
    'instrumentengineer',
    'instrumentmaker',
    'instrumentsupervisor',
    'instrumenttechnician',
    'insurance',
    'insurance agent',
    'insurance assessor',
    'insurance broker',
    'insurance consultant',
    'insurance inspector',
    'insurance staff',
    'insuranceagent',
    'insuranceassessor',
    'insurancebroker',
    'insuranceconsultant',
    'insuranceinspector',
    'insurancestaff',
    'interior decorator',
    'interior designer',
    'interiordecorator',
    'interiordesigner',
    'interpreter',
    'interviewer',
    'inventor',
    'investigator',
    'investment advisor',
    'investment banker',
    'investment manager',
    'investmentadvisor',
    'investmentbanker',
    'investmentmanager',
    'ironmonger',
    'it consultant',
    'it manager',
    'it trainer',
    'itconsultant',
    'itinerant labourer',
    'itinerant trader',
    'itinerantlabourer',
    'itineranttrader',
    'itmanager',
    'ittrainer',
    'janitor',
    'jazz composer',
    'jazzcomposer',
    'jeweller',
    'jewellery',
    'jockey',
    'joiner',
    'joinery consultant',
    'joineryconsultant',
    'journalist',
    'journalistic agent',
    'journalisticagent',
    'judge',
    'junk shop',
    'junkshop',
    'justice of the',
    'justiceofthe',
    'keep fit instructor',
    'keepfitinstructor',
    'kennel hand',
    'kennel maid',
    'kennelhand',
    'kennelmaid',
    'kennels / cattery',
    'kennels/cattery',
    'kissagram person',
    'kissagramperson',
    'kitchen worker',
    'kitchenworker',
    'knitter',
    'labelling operator',
    'labellingoperator',
    'laboratory',
    'laboratory analyst',
    'laboratoryanalyst',
    'labourer',
    'laminator',
    'lampshade maker',
    'lampshademaker',
    'land agent',
    'land surveyor',
    'landagent',
    'landlady',
    'landlord',
    'landowner',
    'landscape',
    'landsurveyor',
    'landworker',
    'lathe operator',
    'latheoperator',
    'laundry staff',
    'laundry worker',
    'laundrystaff',
    'laundryworker',
    'lavatory attendant',
    'lavatoryattendant',
    'law clerk',
    'lawclerk',
    'lawn mower',
    'lawnmower',
    'lawyer',
    'leaflet distributor',
    'leafletdistributor',
    'leather worker',
    'leatherworker',
    'lecturer',
    'ledger clerk',
    'ledgerclerk',
    'legal advisor',
    'legal assistant',
    'legal executive',
    'legal secretary',
    'legaladvisor',
    'legalassistant',
    'legalexecutive',
    'legalsecretary',
    'leisure centre',
    'leisurecentre',
    'lens grinder &',
    'lensgrinder&',
    'letting agent',
    'lettingagent',
    'liaison officer',
    'liaisonofficer',
    'librarian',
    'library manager',
    'librarymanager',
    'licensed',
    'licensee',
    'licensing',
    'lifeguard',
    'lift attendant',
    'lift engineer',
    'liftattendant',
    'liftengineer',
    'lighterman',
    'lighthouse keeper',
    'lighthousekeeper',
    'lighting designer',
    'lighting technician',
    'lightingdesigner',
    'lightingtechnician',
    'lime kiln attendant',
    'limekilnattendant',
    'line manager',
    'line worker',
    'lineman',
    'linemanager',
    'lineworker',
    'linguist',
    'literary agent',
    'literary editor',
    'literaryagent',
    'literaryeditor',
    'lithographer',
    'litigation manager',
    'litigationmanager',
    'loader',
    'loans manager',
    'loansmanager',
    'local government',
    'localgovernment',
    'location',
    'lock keeper',
    'lockkeeper',
    'locksmith',
    'locum pharmacist',
    'locumpharmacist',
    'log merchant',
    'logmerchant',
    'lorry driver',
    'lorrydriver',
    'loss adjustor',
    'loss assessor',
    'lossadjustor',
    'lossassessor',
    'lumberjack',
    'machine',
    'machine fitters',
    'machine minder',
    'machine operator',
    'machine setter',
    'machine tool',
    'machine tool fitter',
    'machinefitters',
    'machineminder',
    'machineoperator',
    'machinesetter',
    'machinetool',
    'machinetoolfitter',
    'machinist',
    'magician',
    'magistrate',
    'magistrates clerk',
    'magistratesclerk',
    'maid',
    'maintenance',
    'maintenance fitter',
    'maintenance man',
    'maintenance staff',
    'maintenancefitter',
    'maintenanceman',
    'maintenancestaff',
    'make up',
    'make up artist',
    'makeup',
    'makeupartist',
    'management',
    'manager',
    'manager sports',
    'managersports',
    'managing director',
    'managingdirector',
    'manicurist',
    'manufacturing',
    'map mounter',
    'mapmounter',
    'marble finisher',
    'marble mason',
    'marblefinisher',
    'marblemason',
    'marine broker',
    'marine consultant',
    'marine electrician',
    'marine engineer',
    'marine geologist',
    'marine pilot',
    'marine surveyor',
    'marinebroker',
    'marineconsultant',
    'marineelectrician',
    'marineengineer',
    'marinegeologist',
    'marinepilot',
    'marinesurveyor',
    'market gardener',
    'market research',
    'market researcher',
    'market trader',
    'marketgardener',
    'marketing',
    'marketing agent',
    'marketing assistant',
    'marketing coordinator',
    'marketing director',
    'marketing manager',
    'marketingagent',
    'marketingassistant',
    'marketingcoordinator',
    'marketingdirector',
    'marketingmanager',
    'marketresearch',
    'marketresearcher',
    'markettrader',
    'marquee erector',
    'marqueeerector',
    'massage therapist',
    'massagetherapist',
    'masseur',
    'masseuse',
    'master mariner',
    'mastermariner',
    'mate',
    'materials controller',
    'materials manager',
    'materialscontroller',
    'materialsmanager',
    'mathematician',
    'matron',
    'mattress maker',
    'mattressmaker',
    'mature student',
    'maturestudent',
    'meat inspector',
    'meat wholesaler',
    'meatinspector',
    'meatwholesaler',
    'mechanic',
    'mechanic airport',
    'mechanic vehicle',
    'mechanicairport',
    'mechanical',
    'mechanicvehicle',
    'medal dealer',
    'medaldealer',
    'medical advisor',
    'medical assistant',
    'medical consultant',
    'medical officer',
    'medical physicist',
    'medical practitioner',
    'medical researcher',
    'medical secretary',
    'medical student',
    'medical supplier',
    'medical technician',
    'medicaladvisor',
    'medicalassistant',
    'medicalconsultant',
    'medicalofficer',
    'medicalphysicist',
    'medicalpractitioner',
    'medicalresearcher',
    'medicalsecretary',
    'medicalstudent',
    'medicalsupplier',
    'medicaltechnician',
    'member of',
    'memberof',
    'merchandiser',
    'merchant',
    'merchant banker',
    'merchant navy',
    'merchant seaman',
    'merchantbanker',
    'merchantnavy',
    'merchantseaman',
    'messenger',
    'metal dealer',
    'metal engineer',
    'metal polisher',
    'metal worker',
    'metaldealer',
    'metalengineer',
    'metallurgist',
    'metalpolisher',
    'metalworker',
    'meteorologist',
    'meter reader',
    'meterreader',
    'microbiologist',
    'microfilm operator',
    'microfilmoperator',
    'midwife',
    'milklady',
    'milkman',
    'mill operator',
    'mill worker',
    'miller',
    'milliner',
    'milloperator',
    'millworker',
    'millwright',
    'miner',
    'mineralologist',
    'minibus driver',
    'minibusdriver',
    'minicab driver',
    'minicabdriver',
    'mining consultant',
    'mining engineer',
    'miningconsultant',
    'miningengineer',
    'minister of religion',
    'ministerofreligion',
    'missionary',
    'mobile caterer',
    'mobile disc jockey',
    'mobile disco owner',
    'mobile hairdresser',
    'mobile motor',
    'mobile service',
    'mobilecaterer',
    'mobilediscjockey',
    'mobilediscoowner',
    'mobilehairdresser',
    'mobilemotor',
    'mobileservice',
    'model',
    'model maker',
    'modelmaker',
    'money broker',
    'money dealer',
    'moneybroker',
    'moneydealer',
    'moneylender',
    'monumental',
    'mooring contractor',
    'mooringcontractor',
    'mortgage',
    'mortgage broker',
    'mortgagebroker',
    'mortician',
    'motor dealer',
    'motor engineer',
    'motor fitter',
    'motor mechanic',
    'motor racing',
    'motor trader',
    'motorcyclist',
    'motordealer',
    'motorengineer',
    'motorfitter',
    'motormechanic',
    'motorracing',
    'motortrader',
    'museum',
    'museum assistant',
    'museum attendant',
    'museumassistant',
    'museumattendant',
    'music teacher',
    'music therapist',
    'music wholesaler',
    'musician',
    'musicteacher',
    'musictherapist',
    'musicwholesaler',
    'nanny',
    'naturopath',
    'navigator',
    'navy',
    'negotiator',
    'neurologist',
    'newsagent',
    'night club staff',
    'night porter',
    'night watchman',
    'nightclubstaff',
    'nightporter',
    'nightwatchman',
    'non commissioned officer',
    'non motor trade',
    'noncommissionedofficer',
    'nonmotortrade',
    'notary public',
    'notarypublic',
    'nuclear scientist',
    'nuclearscientist',
    'nun',
    'nurse',
    'nursery assistant',
    'nursery nurse',
    'nursery worker',
    'nurseryassistant',
    'nurseryman',
    'nurserynurse',
    'nurseryworker',
    'nursing assistant',
    'nursing auxiliary',
    'nursing manager',
    'nursing sister',
    'nursingassistant',
    'nursingauxiliary',
    'nursingmanager',
    'nursingsister',
    'nutritionist',
    'occupational',
    'off shore',
    'office',
    'office manager',
    'office worker',
    'officemanager',
    'officer',
    'officeworker',
    'offshore',
    'oil broker',
    'oil rig crew',
    'oilbroker',
    'oilrigcrew',
    'opera singer',
    'operasinger',
    'operations',
    'operative',
    'operator',
    'opthalmic',
    'optical',
    'optical advisor',
    'optical assistant',
    'opticaladvisor',
    'opticalassistant',
    'optician',
    'optometrist',
    'orchestral',
    'order clerk',
    'orderclerk',
    'organiser',
    'organist',
    'ornamental',
    'ornithologist',
    'orthopaedic',
    'orthoptist',
    'osteopath',
    'ostler',
    'outdoor pursuits',
    'outdoorpursuits',
    'outfitter',
    'outreach worker',
    'outreachworker',
    'overhead',
    'overhead line',
    'overheadline',
    'overlocker',
    'overseas mailer',
    'overseasmailer',
    'overwriter',
    'owner',
    'packaging',
    'packer',
    'paediatrician',
    'pager operator',
    'pageroperator',
    'paint consultant',
    'paint sprayer',
    'paintconsultant',
    'painter',
    'painter and',
    'painterand',
    'paintsprayer',
    'palaeobotanist',
    'palaeontologist',
    'pallet maker',
    'palletmaker',
    'panel beater',
    'panelbeater',
    'paper mill',
    'papermill',
    'parachute',
    'paramedic',
    'park attendant',
    'park keeper',
    'park ranger',
    'park/',
    'parkattendant',
    'parkkeeper',
    'parkranger',
    'parliament',
    'partition erector',
    'partitionerector',
    'parts man',
    'parts manager',
    'parts supervisor',
    'partsman',
    'partsmanager',
    'partssupervisor',
    'party planner',
    'partyplanner',
    'pasteuriser',
    'pastry chef',
    'pastrychef',
    'patent agent',
    'patent attorney',
    'patentagent',
    'patentattorney',
    'pathologist',
    'patrol person',
    'patrolman',
    'patrolperson',
    'pattern cutter',
    'pattern maker',
    'pattern weaver',
    'patterncutter',
    'patternmaker',
    'patternweaver',
    'paviour',
    'pawnbroker',
    'payment officer',
    'paymentofficer',
    'payroll assistant',
    'payroll clerk',
    'payroll manager',
    'payroll supervisor',
    'payrollassistant',
    'payrollclerk',
    'payrollmanager',
    'payrollsupervisor',
    'peace',
    'pearl stringer',
    'pearlstringer',
    'pensions',
    'performer',
    'personal',
    'personnel',
    'personnel officer',
    'personnelofficer',
    'pest control',
    'pest controller',
    'pestcontrol',
    'pestcontroller',
    'pet minder',
    'petminder',
    'petrol station',
    'petroleum',
    'petrolstation',
    'petty officer',
    'pettyofficer',
    'pharmaceutical',
    'pharmacist',
    'pharmacy',
    'philatelist',
    'photo engraver',
    'photo laboratory',
    'photo technician',
    'photocopy',
    'photoengraver',
    'photographer',
    'photographic',
    'photolaboratory',
    'phototechnician',
    'physician',
    'physicist',
    'physiologist',
    'physiotherapist',
    'piano tuner',
    'pianotuner',
    'picker',
    'picture editor',
    'picture framer',
    'picture reseacher',
    'pictureeditor',
    'pictureframer',
    'picturereseacher',
    'pig man',
    'pig manager',
    'pigman',
    'pigmanager',
    'pilot',
    'pipe fitter',
    'pipe inspector',
    'pipe insulator',
    'pipe layer',
    'pipefitter',
    'pipeinspector',
    'pipeinsulator',
    'pipelayer',
    'planning engineer',
    'planning manager',
    'planning officer',
    'planning technician',
    'planningengineer',
    'planningmanager',
    'planningofficer',
    'planningtechnician',
    'plant attendant',
    'plant driver',
    'plant engineer',
    'plant fitter',
    'plant manager',
    'plant operator',
    'plantattendant',
    'plantdriver',
    'plantengineer',
    'plantfitter',
    'plantmanager',
    'plantoperator',
    'plasterer',
    'plastics consultant',
    'plastics engineer',
    'plasticsconsultant',
    'plasticsengineer',
    'plate layer',
    'platelayer',
    'plater',
    'playgroup assistant',
    'playgroup leader',
    'playgroupassistant',
    'playgroupleader',
    'plumber',
    'plumbing & heating',
    'plumbing&heating',
    'podiatrist',
    'police officer',
    'policeofficer',
    'polisher',
    'pool attendant',
    'poolattendant',
    'pools collector',
    'poolscollector',
    'porter',
    'portfolio manager',
    'portfoliomanager',
    'post card seller',
    'post office counter clerk',
    'post office staff',
    'post sorter',
    'postcardseller',
    'postman',
    'postman/woman',
    'postmaster',
    'postofficecounterclerk',
    'postofficestaff',
    'postsorter',
    'postwoman',
    'potato merchant',
    'potatomerchant',
    'potter',
    'practice manager',
    'practicemanager',
    'preacher',
    'precision engineer',
    'precisionengineer',
    'premises',
    'premises security',
    'premisessecurity',
    'press officer',
    'press operator',
    'press setter',
    'presser',
    'pressofficer',
    'pressoperator',
    'presssetter',
    'priest',
    'print finisher',
    'printer',
    'printfinisher',
    'prison chaplain',
    'prison officer',
    'prisonchaplain',
    'prisonofficer',
    'private investigator',
    'privateinvestigator',
    'probation officer',
    'probation worker',
    'probationofficer',
    'probationworker',
    'process engineer',
    'process operator',
    'process worker',
    'processengineer',
    'processoperator',
    'processor',
    'processworker',
    'procurator fiscal',
    'procuratorfiscal',
    'produce supervisor',
    'producer',
    'producesupervisor',
    'product installer',
    'product manager',
    'productinstaller',
    'production engineer',
    'production hand',
    'production manager',
    'production planner',
    'productionengineer',
    'productionhand',
    'productionmanager',
    'productionplanner',
    'productmanager',
    'professional',
    'professional boxer',
    'professional racing',
    'professional wrestler',
    'professionalboxer',
    'professionalracing',
    'professionalwrestler',
    'professor',
    'programmer',
    'progress chaser',
    'progress clerk',
    'progresschaser',
    'progressclerk',
    'project co ordinator',
    'project engineer',
    'project leader',
    'project manager',
    'project worker',
    'projectcoordinator',
    'projectengineer',
    'projectionist',
    'projectleader',
    'projectmanager',
    'projectworker',
    'promoter',
    'proof reader',
    'proofreader',
    'property buyer',
    'property dealer',
    'property developer',
    'property manager',
    'property valuer',
    'propertybuyer',
    'propertydealer',
    'propertydeveloper',
    'propertymanager',
    'propertyvaluer',
    'proprietor',
    'psychiatrist',
    'psychoanalyst',
    'psychologist',
    'psychotherapist',
    'psycodynamic',
    'public house manager',
    'public relations officer',
    'publican',
    'publichousemanager',
    'publicity manager',
    'publicitymanager',
    'publicrelationsofficer',
    'publisher',
    'publishing manager',
    'publishingmanager',
    'purchase clerk',
    'purchase ledger clerk',
    'purchaseclerk',
    'purchaseledgerclerk',
    'purchasing assistant',
    'purchasing manager',
    'purchasingassistant',
    'purchasingmanager',
    'purser',
    'quality controller',
    'quality engineer',
    'quality inspector',
    'quality manager',
    'quality technician',
    'qualitycontroller',
    'qualityengineer',
    'qualityinspector',
    'qualitymanager',
    'qualitytechnician',
    'quantity surveyor',
    'quantitysurveyor',
    'quarry worker',
    'quarryworker',
    'queens council',
    'queenscouncil',
    'rabbi',
    'racehorse groom',
    'racehorsegroom',
    'racing organiser',
    'racingorganiser',
    'radio controller',
    'radio director',
    'radio engineer',
    'radio operator',
    'radio presenter',
    'radio producer',
    'radiocontroller',
    'radiodirector',
    'radioengineer',
    'radiographer',
    'radiologist',
    'radiooperator',
    'radiopresenter',
    'radioproducer',
    'railway staff',
    'railwaystaff',
    'rally driver',
    'rallydriver',
    'ramp agent',
    'rampagent',
    'ranger',
    'receptionist',
    'recorder',
    'records supervisor',
    'recordssupervisor',
    'recovery vehicle coordinator',
    'recoveryvehiclecoordinator',
    'recreational',
    'recruitment consultant',
    'recruitmentconsultant',
    'rector',
    'refigeration engineer',
    'refigerationengineer',
    'refit merchandiser',
    'refitmerchandiser',
    'reflexologist',
    'refractory engineer',
    'refractoryengineer',
    'refuse collector',
    'refusecollector',
    'registrar',
    'regulator',
    'relocation agent',
    'relocationagent',
    'remedial therapist',
    'remedialtherapist',
    'rent collector',
    'rent officer',
    'rentcollector',
    'rentofficer',
    'repair man',
    'repairer',
    'repairman',
    'reporter',
    'representative',
    'reprographic assistant',
    'reprographicassistant',
    'research analyst',
    'research consultant',
    'research director',
    'research scientist',
    'research technician',
    'researchanalyst',
    'researchconsultant',
    'researchdirector',
    'researcher',
    'researchscientist',
    'researchtechnician',
    'resin caster',
    'resincaster',
    'restaurant manager',
    'restaurantmanager',
    'restaurateur',
    'restorer',
    'retired',
    'revenue clerk',
    'revenue officer',
    'revenueclerk',
    'revenueofficer',
    'riding instructor',
    'ridinginstructor',
    'rig worker',
    'rig worker off shore',
    'rigger',
    'rigworker',
    'rigworkeroffshore',
    'riveter',
    'road safety officer',
    'road sweeper',
    'road worker',
    'roadsafetyofficer',
    'roadsweeper',
    'roadworker',
    'roof tiler',
    'roofer',
    'rooftiler',
    'rose grower',
    'rosegrower',
    'royal marine',
    'royalmarine',
    'rug maker',
    'rugmaker',
    'saddler',
    'safety officer',
    'safetyofficer',
    'sail maker',
    'sailmaker',
    'sales administrator',
    'sales assistant',
    'sales director',
    'sales engineer',
    'sales executive',
    'sales manager',
    'sales non travelling',
    'sales representative',
    'sales support',
    'sales travelling',
    'sales woman',
    'salesadministrator',
    'salesassistant',
    'salesdirector',
    'salesengineer',
    'salesexecutive',
    'salesman',
    'salesmanager',
    'salesnontravelling',
    'salesrepresentative',
    'salessupport',
    'salestravelling',
    'saleswoman',
    'sand blaster',
    'sandblaster',
    'saw miller',
    'sawmiller',
    'scaffolder',
    'school crossing',
    'school inspector',
    'schoolcrossing',
    'schoolinspector',
    'scientific officer',
    'scientificofficer',
    'scientist',
    'scrap dealer',
    'scrapdealer',
    'screen printer',
    'screen writer',
    'screenprinter',
    'screenwriter',
    'script writer',
    'scriptwriter',
    'sculptor',
    'seaman',
    'seamstress',
    'second hand',
    'secondhand',
    'secretary',
    'secretary and pa',
    'secretaryandpa',
    'security consultant',
    'security controller',
    'security guard',
    'security officer',
    'securityconsultant',
    'securitycontroller',
    'securityguard',
    'securityofficer',
    'seedsman',
    'semi professional',
    'semiprofessional',
    'servant',
    'service engineer',
    'service manager',
    'serviceengineer',
    'servicemanager',
    'share dealer',
    'sharedealer',
    'sheet metal worker',
    'sheetmetalworker',
    'shelf filler',
    'shelffiller',
    'shelter warden',
    'shelterwarden',
    'shepherd',
    'sheriff',
    'sheriff clerk',
    'sheriff principal',
    'sheriffclerk',
    'sheriffprincipal',
    'sheriffs officer',
    'sheriffsofficer',
    'shift controller',
    'shiftcontroller',
    'ship broker',
    'ship builder',
    'shipbroker',
    'shipbuilder',
    'shipping clerk',
    'shipping officer',
    'shippingclerk',
    'shippingofficer',
    'shipwright',
    'shipyard worker',
    'shipyardworker',
    'shoe maker',
    'shoe repairer',
    'shoemaker',
    'shoerepairer',
    'shooting instructor',
    'shootinginstructor',
    'shop',
    'shop assistant',
    'shop fitter',
    'shop keeper',
    'shop manager',
    'shop proprietor',
    'shopassistant',
    'shopfitter',
    'shopkeeper',
    'shopmanager',
    'shopproprietor',
    'shot blaster',
    'shotblaster',
    'show jumper',
    'showjumper',
    'showman',
    'shunter',
    'sign maker',
    'signalman',
    'signmaker',
    'signwriter',
    'singer',
    'site agent',
    'site engineer',
    'siteagent',
    'siteengineer',
    'skipper',
    'slater',
    'slaughterman',
    'smallholder',
    'social worker',
    'socialworker',
    'software consultant',
    'software engineer',
    'softwareconsultant',
    'softwareengineer',
    'soldier',
    'solicitor',
    'song writer',
    'songwriter',
    'sorter',
    'sound engineer',
    'sound technician',
    'soundengineer',
    'soundtechnician',
    'source insurance limited',
    'sourceinsurancelimited',
    'special constable',
    'special needs',
    'specialconstable',
    'specialneeds',
    'speech therapist',
    'speechtherapist',
    'sports administrator',
    'sports centre',
    'sports coach',
    'sports commentator',
    'sportsadministrator',
    'sportscentre',
    'sportscoach',
    'sportscommentator',
    'sportsman',
    'sportsperson',
    'sportswoman',
    'spring maker',
    'springmaker',
    'stable hand',
    'stablehand',
    'staff',
    'staff nurse',
    'staffnurse',
    'stage director',
    'stage hand',
    'stage manager',
    'stage mover',
    'stagedirector',
    'stagehand',
    'stagemanager',
    'stagemover',
    'station manager',
    'stationer',
    'stationmanager',
    'statistician',
    'steel erector',
    'steel worker',
    'steelerector',
    'steelworker',
    'steeplejack',
    'stenographer',
    'stevedore',
    'steward',
    'stewardess',
    'stock controller',
    'stock manager',
    'stockbroker',
    'stockcontroller',
    'stockman',
    'stockmanager',
    'stocktaker',
    'stone cutter',
    'stone sawyer',
    'stonecutter',
    'stonemason',
    'stonesawyer',
    'store detective',
    'storedetective',
    'storeman',
    'storewoman',
    'street entertainer',
    'street trader',
    'streetentertainer',
    'streettrader',
    'stud hand',
    'student',
    'student nurse',
    'student teacher',
    'studentnurse',
    'studentteacher',
    'studhand',
    'studio',
    'studio manager',
    'studiomanager',
    'sub postmaster',
    'sub postmistress',
    'subpostmaster',
    'subpostmistress',
    'supervisor',
    'supply teacher',
    'supplyteacher',
    'surgeon',
    'surveyor',
    'systems analyst',
    'systems manager',
    'systemsanalyst',
    'systemsmanager',
    't shirt printer',
    'tachograph analyst',
    'tachographanalyst',
    'tacker',
    'tailor',
    'tank farm operative',
    'tanker driver',
    'tankerdriver',
    'tankfarmoperative',
    'tanner',
    'tarmacer',
    'tarot reader/palmistry',
    'tarotreader/palmistry',
    'tattooist',
    'tax advisor',
    'tax analyst',
    'tax assistant',
    'tax consultant',
    'tax inspector',
    'tax manager',
    'tax officer',
    'taxadvisor',
    'taxanalyst',
    'taxassistant',
    'taxconsultant',
    'taxi controller',
    'taxi driver',
    'taxicontroller',
    'taxidermist',
    'taxidriver',
    'taxinspector',
    'taxmanager',
    'taxofficer',
    'tea blender',
    'tea taster',
    'teablender',
    'teacher',
    'teachers assistant',
    'teachersassistant',
    'teataster',
    'technical advisor',
    'technical analyst',
    'technical assistant',
    'technical author',
    'technical clerk',
    'technical co ordinator',
    'technical director',
    'technical editor',
    'technical engineer',
    'technical illustrator',
    'technical instructor',
    'technical liaison',
    'technical manager',
    'technicaladvisor',
    'technicalanalyst',
    'technicalassistant',
    'technicalauthor',
    'technicalclerk',
    'technicalcoordinator',
    'technicaldirector',
    'technicaleditor',
    'technicalengineer',
    'technicalillustrator',
    'technicalinstructor',
    'technicalliaison',
    'technicalmanager',
    'technician',
    'telecommunication',
    'telegraphist',
    'telemarketeer',
    'telephone engineer',
    'telephoneengineer',
    'telephonist',
    'telesales person',
    'telesalesperson',
    'television director',
    'television engineer',
    'television presenter',
    'television producer',
    'televisiondirector',
    'televisionengineer',
    'televisionpresenter',
    'televisionproducer',
    'telex operator',
    'telexoperator',
    'temperature time',
    'temperaturetime',
    'tennis coach',
    'tenniscoach',
    'textile consultant',
    'textile engineer',
    'textile technician',
    'textile worker',
    'textileconsultant',
    'textileengineer',
    'textiletechnician',
    'textileworker',
    'thatcher',
    'theatre manager',
    'theatre technician',
    'theatremanager',
    'theatretechnician',
    'theatrical agent',
    'theatricalagent',
    'therapist',
    'thermal engineer',
    'thermal insulator',
    'thermalengineer',
    'thermalinsulator',
    'ticket agent',
    'ticket inspector',
    'ticketagent',
    'ticketinspector',
    'tiler',
    'timber inspector',
    'timber worker',
    'timberinspector',
    'timberworker',
    'tobacconist',
    'toll collector',
    'tollcollector',
    'tool maker',
    'tool setter',
    'toolmaker',
    'toolsetter',
    'tour agent',
    'tour guide',
    'touragent',
    'tourguide',
    'town clerk',
    'town planner',
    'townclerk',
    'townplanner',
    'toy maker',
    'toy trader',
    'toymaker',
    'toytrader',
    'track worker',
    'trackworker',
    'tractor driver',
    'tractor mechanic',
    'tractordriver',
    'tractormechanic',
    'trade mark agent',
    'trade union official',
    'trademarkagent',
    'tradeunionofficial',
    'trading standards',
    'tradingstandards',
    'traffic clerk',
    'traffic engineer',
    'traffic officer',
    'traffic planner',
    'traffic supervisor',
    'traffic warden',
    'trafficclerk',
    'trafficengineer',
    'trafficofficer',
    'trafficplanner',
    'trafficsupervisor',
    'trafficwarden',
    'train driver',
    'traindriver',
    'trainee',
    'trainee manager',
    'traineemanager',
    'trainer',
    'training advisor',
    'training assistant',
    'training co ordinator',
    'training consultant',
    'training instructor',
    'training manager',
    'training officer',
    'trainingadvisor',
    'trainingassistant',
    'trainingconsultant',
    'trainingcoordinator',
    'traininginstructor',
    'trainingmanager',
    'trainingofficer',
    'transcriber',
    'translator',
    'transport clerk',
    'transport consultant',
    'transport controller',
    'transport engineer',
    'transport manager',
    'transport officer',
    'transport planner',
    'transportclerk',
    'transportconsultant',
    'transportcontroller',
    'transportengineer',
    'transportmanager',
    'transportofficer',
    'transportplanner',
    'travel agent',
    'travel clerk',
    'travel consultant',
    'travel courier',
    'travel guide',
    'travel guide writer',
    'travel representative',
    'travelagent',
    'travelclerk',
    'travelconsultant',
    'travelcourier',
    'travelguide',
    'travelguidewriter',
    'travelling showman',
    'travellingshowman',
    'travelrepresentative',
    'treasurer',
    'tree feller',
    'tree surgeon',
    'treefeller',
    'treesurgeon',
    'trichologist',
    'trinity house pilot',
    'trinityhousepilot',
    'trout farmer',
    'troutfarmer',
    'tshirtprinter',
    'tug skipper',
    'tugskipper',
    'tunneller',
    'turf accountant',
    'turfaccountant',
    'turkey farmer',
    'turkeyfarmer',
    'turner',
    'tutor',
    'tv and video installer',
    'tv and video repairer',
    'tv editor',
    'tvandvideoinstaller',
    'tvandvideorepairer',
    'tveditor',
    'typesetter',
    'typewriter engineer',
    'typewriterengineer',
    'typist',
    'tyre builder',
    'tyre fitter',
    'tyre inspector',
    'tyre technician',
    'tyrebuilder',
    'tyrefitter',
    'tyreinspector',
    'tyretechnician',
    'undertaker',
    'underwriter',
    'underwriting',
    'unemployed',
    'unlicensed',
    'unlicensed premises',
    'unlicensedpremises',
    'upholsterer',
    'usher',
    'valuer',
    'valve technician',
    'valvetechnician',
    'van driver',
    'vandriver',
    'vdu operator',
    'vduoperator',
    'vehicle assessor',
    'vehicle body worker',
    'vehicle engineer',
    'vehicle technician',
    'vehicleassessor',
    'vehiclebodyworker',
    'vehicleengineer',
    'vehicletechnician',
    'vending machine',
    'vending machine filler',
    'vendingmachine',
    'vendingmachinefiller',
    'ventriloquist',
    'verger',
    'veterinary surgeon',
    'veterinarysurgeon',
    'vicar',
    'violin maker',
    'violinist',
    'violinmaker',
    'voluntary worker',
    'voluntaryworker',
    'w w w . t h e s o u r c e . c o . u kpsychologist',
    'wages clerk',
    'wagesclerk',
    'waiter',
    'waitress',
    'warden',
    'warehouse manager',
    'warehouseman',
    'warehouseman/woman',
    'warehousemanager',
    'warehousewoman',
    'waste dealer',
    'wastedealer',
    'watchmaker',
    'water industry worker',
    'waterindustryworker',
    'weaver',
    'weighbridge clerk',
    'weighbridge operator',
    'weighbridgeclerk',
    'weighbridgeoperator',
    'welder',
    'welfare assistant',
    'welfare officer',
    'welfare rights officer',
    'welfareassistant',
    'welfareofficer',
    'welfarerightsofficer',
    'wheel clamper',
    'wheelclamper',
    'wholesale newspaper',
    'wholesalenewspaper',
    'window cleaner',
    'window dresser',
    'windowcleaner',
    'windowdresser',
    'windscreen fitter',
    'windscreenfitter',
    'wine merchant',
    'winemerchant',
    'wood carver',
    'wood cutter',
    'wood worker',
    'woodcarver',
    'woodcutter',
    'woodworker',
    'word processing operator',
    'wordprocessingoperator',
    'worker',
    'works manager',
    'worksmanager',
    'writer',
    'www.thesource.co.ukpsychologist',
    'yacht master',
    'yachtmaster',
    'yard manager',
    'yardmanager',
    'youth hostel warden',
    'youth worker',
    'youthhostelwarden',
    'youthworker',
    'zoo keeper',
    'zoo manager',
    'zookeeper',
    'zoologist',
    'zoology consultant',
    'zoologyconsultant',
    'zoomanager',
    'terrorist',
    'football player',
    'basketball player',
    'actor',
    'queen',
    'king',
    'prince',
    'princess',
    'lord',
    'baron',
    'minister',
    'prime minister',
    'superstars',
    'superstar',
    'star',
    
])
